# Site settings
title: Blood Donors | Rotaract 3190
url: "https://blood.rotaract3190.org" # the base hostname & protocol for your site
baseurl: ""
timezone: Asia/Kolkata

icon: /assets/img/logo.png

og_img: /assets/img/final.png

description: 3190 Blood Donors initiative is focused on helping the community with information of the Volunteers who are willing to donate blood.

# Build settings
markdown: kramdown
# highlighter: rouge
# permalink: blog/:year/:month/:day/:title/
# paginate: 4
# paginate_path: blog/page-:num/

# Google analytics
ga_tracking_id: "G-Q6KH36RK4V"

plugins:
  - jekyll-sitemap
  - jekyll-feed

collections:
  bloodgroups:
    output: true
    permalink: /:path/

include:
  - _redirects